name: Docker build and deploy

on:
  push:
    branches: [main]

env:
  AWS_REGION: us-west-2

jobs:
  build_and_push_to_ecr:
    runs-on: ubuntu-latest
    environment: Demo
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.ECR_DEMO_PUSH_ROLE }}
        role-session-name: BlockhouseDemo
        aws-region: ${{ env.AWS_REGION }}
    - name: Sts GetCallerIdentity
      run: |
        aws sts get-caller-identity

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push docker image to Amazon ECR
      run: |
        echo "Building docker image"
        docker build . --file Dockerfile --tag blockhouse_oa --platform linux/amd64/v3
        echo "Tagging docker image"
        docker tag blockhouse_oa:latest 522814699715.dkr.ecr.us-west-2.amazonaws.com/blockhouse_oa:latest
        echo "Pushing docker image to to ECR for ${{ github.event.inputs.environment }}"
        docker push 522814699715.dkr.ecr.us-west-2.amazonaws.com/blockhouse_oa:latest

    - name: SSH into EC2 and deploy
      uses: appleboy/ssh-action@v1.2.1
      with:
        host: ${{ secrets.EC2_HOSTNAME }}
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.EC2_SSH_PORT }}
        script: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin 522814699715.dkr.ecr.region.amazonaws.com
          docker pull 522814699715.dkr.ecr.us-west-2.amazonaws.com/blockhouse_oa
          docker restart ${{ secrets.CONTAINER_ID }}
